//sale
export const ADD_SALE_RECORD = "ADD_SALE_RECORD"
export const SET_SALE_RECORD = "SET_SALE_RECORD"

//service
export const ADD_SERVICE = "ADD_SERVICE"
export const SET_SERVICE = "SET_SERVICE"
export const UPDATE_SERVICE = "UPDATE_SERVICE"
export const DELETE_SERVICE = "DELETE_SERVICE"


export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const SET_EMPLOYEE = "SET_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"

export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const SET_SCHEDULE = "SET_SCHEDULE";


export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_PRODUCT = "SET_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SEARCH_TYPE = "SEARCH_TYPE";
export const SEARCH_NUMBER = "SEARCH_NUMBER";

export const SET_TOKEN = "SET_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN"

